// <auto-generated />
using System;
using CovautoAPI.Domain.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CovautoAPI.Domain.Migrations
{
    [DbContext(typeof(CovautoContext))]
    [Migration("20250516090544_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("CovautoAPI.Domain.Entities.LeenAuto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Kenteken")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("KilometerStand")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("leenAutos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Kenteken = "AB-123-CD",
                            KilometerStand = 15000
                        },
                        new
                        {
                            Id = 2,
                            Kenteken = "EF-456-GH",
                            KilometerStand = 20000
                        },
                        new
                        {
                            Id = 3,
                            Kenteken = "IJ-789-KL",
                            KilometerStand = 25000
                        });
                });

            modelBuilder.Entity("CovautoAPI.Domain.Entities.ReserveringData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("KilometerStand")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ReserveringID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StartPostcode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StartStad")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StartStraat")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ToPostcode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ToStad")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ToStraat")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ReserveringData");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            KilometerStand = 15000,
                            ReserveringID = 1,
                            StartPostcode = "1234AA",
                            StartStad = "Startstad",
                            StartStraat = "Startstraat 0",
                            ToPostcode = "5678BB",
                            ToStad = "Bestemmingstad",
                            ToStraat = "Bestemmingstraat 0"
                        },
                        new
                        {
                            Id = 2,
                            KilometerStand = 15020,
                            ReserveringID = 1,
                            StartPostcode = "1234AB",
                            StartStad = "Startstad B",
                            StartStraat = "Startstraat 0B",
                            ToPostcode = "5678BC",
                            ToStad = "Bestemmingstad B",
                            ToStraat = "Bestemmingstraat 0B"
                        },
                        new
                        {
                            Id = 3,
                            KilometerStand = 15100,
                            ReserveringID = 2,
                            StartPostcode = "1234AA",
                            StartStad = "Startstad",
                            StartStraat = "Startstraat 1",
                            ToPostcode = "5678BB",
                            ToStad = "Bestemmingstad",
                            ToStraat = "Bestemmingstraat 1"
                        },
                        new
                        {
                            Id = 4,
                            KilometerStand = 15120,
                            ReserveringID = 2,
                            StartPostcode = "1234AB",
                            StartStad = "Startstad B",
                            StartStraat = "Startstraat 1B",
                            ToPostcode = "5678BC",
                            ToStad = "Bestemmingstad B",
                            ToStraat = "Bestemmingstraat 1B"
                        },
                        new
                        {
                            Id = 5,
                            KilometerStand = 15200,
                            ReserveringID = 3,
                            StartPostcode = "1234AA",
                            StartStad = "Startstad",
                            StartStraat = "Startstraat 2",
                            ToPostcode = "5678BB",
                            ToStad = "Bestemmingstad",
                            ToStraat = "Bestemmingstraat 2"
                        },
                        new
                        {
                            Id = 6,
                            KilometerStand = 15220,
                            ReserveringID = 3,
                            StartPostcode = "1234AB",
                            StartStad = "Startstad B",
                            StartStraat = "Startstraat 2B",
                            ToPostcode = "5678BC",
                            ToStad = "Bestemmingstad B",
                            ToStraat = "Bestemmingstraat 2B"
                        },
                        new
                        {
                            Id = 7,
                            KilometerStand = 15300,
                            ReserveringID = 4,
                            StartPostcode = "1234AA",
                            StartStad = "Startstad",
                            StartStraat = "Startstraat 3",
                            ToPostcode = "5678BB",
                            ToStad = "Bestemmingstad",
                            ToStraat = "Bestemmingstraat 3"
                        },
                        new
                        {
                            Id = 8,
                            KilometerStand = 15320,
                            ReserveringID = 4,
                            StartPostcode = "1234AB",
                            StartStad = "Startstad B",
                            StartStraat = "Startstraat 3B",
                            ToPostcode = "5678BC",
                            ToStad = "Bestemmingstad B",
                            ToStraat = "Bestemmingstraat 3B"
                        },
                        new
                        {
                            Id = 9,
                            KilometerStand = 15400,
                            ReserveringID = 5,
                            StartPostcode = "1234AA",
                            StartStad = "Startstad",
                            StartStraat = "Startstraat 4",
                            ToPostcode = "5678BB",
                            ToStad = "Bestemmingstad",
                            ToStraat = "Bestemmingstraat 4"
                        },
                        new
                        {
                            Id = 10,
                            KilometerStand = 15420,
                            ReserveringID = 5,
                            StartPostcode = "1234AB",
                            StartStad = "Startstad B",
                            StartStraat = "Startstraat 4B",
                            ToPostcode = "5678BC",
                            ToStad = "Bestemmingstad B",
                            ToStraat = "Bestemmingstraat 4B"
                        },
                        new
                        {
                            Id = 11,
                            KilometerStand = 15500,
                            ReserveringID = 6,
                            StartPostcode = "1234AA",
                            StartStad = "Startstad",
                            StartStraat = "Startstraat 5",
                            ToPostcode = "5678BB",
                            ToStad = "Bestemmingstad",
                            ToStraat = "Bestemmingstraat 5"
                        },
                        new
                        {
                            Id = 12,
                            KilometerStand = 15520,
                            ReserveringID = 6,
                            StartPostcode = "1234AB",
                            StartStad = "Startstad B",
                            StartStraat = "Startstraat 5B",
                            ToPostcode = "5678BC",
                            ToStad = "Bestemmingstad B",
                            ToStraat = "Bestemmingstraat 5B"
                        },
                        new
                        {
                            Id = 13,
                            KilometerStand = 15600,
                            ReserveringID = 7,
                            StartPostcode = "1234AA",
                            StartStad = "Startstad",
                            StartStraat = "Startstraat 6",
                            ToPostcode = "5678BB",
                            ToStad = "Bestemmingstad",
                            ToStraat = "Bestemmingstraat 6"
                        },
                        new
                        {
                            Id = 14,
                            KilometerStand = 15620,
                            ReserveringID = 7,
                            StartPostcode = "1234AB",
                            StartStad = "Startstad B",
                            StartStraat = "Startstraat 6B",
                            ToPostcode = "5678BC",
                            ToStad = "Bestemmingstad B",
                            ToStraat = "Bestemmingstraat 6B"
                        },
                        new
                        {
                            Id = 15,
                            KilometerStand = 15700,
                            ReserveringID = 8,
                            StartPostcode = "1234AA",
                            StartStad = "Startstad",
                            StartStraat = "Startstraat 7",
                            ToPostcode = "5678BB",
                            ToStad = "Bestemmingstad",
                            ToStraat = "Bestemmingstraat 7"
                        },
                        new
                        {
                            Id = 16,
                            KilometerStand = 15720,
                            ReserveringID = 8,
                            StartPostcode = "1234AB",
                            StartStad = "Startstad B",
                            StartStraat = "Startstraat 7B",
                            ToPostcode = "5678BC",
                            ToStad = "Bestemmingstad B",
                            ToStraat = "Bestemmingstraat 7B"
                        },
                        new
                        {
                            Id = 17,
                            KilometerStand = 15000,
                            ReserveringID = 9,
                            StartPostcode = "1234AA",
                            StartStad = "Startstad",
                            StartStraat = "Startstraat 0",
                            ToPostcode = "5678BB",
                            ToStad = "Bestemmingstad",
                            ToStraat = "Bestemmingstraat 0"
                        },
                        new
                        {
                            Id = 18,
                            KilometerStand = 15020,
                            ReserveringID = 9,
                            StartPostcode = "1234AB",
                            StartStad = "Startstad B",
                            StartStraat = "Startstraat 0B",
                            ToPostcode = "5678BC",
                            ToStad = "Bestemmingstad B",
                            ToStraat = "Bestemmingstraat 0B"
                        },
                        new
                        {
                            Id = 19,
                            KilometerStand = 15100,
                            ReserveringID = 10,
                            StartPostcode = "1234AA",
                            StartStad = "Startstad",
                            StartStraat = "Startstraat 1",
                            ToPostcode = "5678BB",
                            ToStad = "Bestemmingstad",
                            ToStraat = "Bestemmingstraat 1"
                        },
                        new
                        {
                            Id = 20,
                            KilometerStand = 15120,
                            ReserveringID = 10,
                            StartPostcode = "1234AB",
                            StartStad = "Startstad B",
                            StartStraat = "Startstraat 1B",
                            ToPostcode = "5678BC",
                            ToStad = "Bestemmingstad B",
                            ToStraat = "Bestemmingstraat 1B"
                        },
                        new
                        {
                            Id = 21,
                            KilometerStand = 15200,
                            ReserveringID = 11,
                            StartPostcode = "1234AA",
                            StartStad = "Startstad",
                            StartStraat = "Startstraat 2",
                            ToPostcode = "5678BB",
                            ToStad = "Bestemmingstad",
                            ToStraat = "Bestemmingstraat 2"
                        },
                        new
                        {
                            Id = 22,
                            KilometerStand = 15220,
                            ReserveringID = 11,
                            StartPostcode = "1234AB",
                            StartStad = "Startstad B",
                            StartStraat = "Startstraat 2B",
                            ToPostcode = "5678BC",
                            ToStad = "Bestemmingstad B",
                            ToStraat = "Bestemmingstraat 2B"
                        },
                        new
                        {
                            Id = 23,
                            KilometerStand = 15300,
                            ReserveringID = 12,
                            StartPostcode = "1234AA",
                            StartStad = "Startstad",
                            StartStraat = "Startstraat 3",
                            ToPostcode = "5678BB",
                            ToStad = "Bestemmingstad",
                            ToStraat = "Bestemmingstraat 3"
                        },
                        new
                        {
                            Id = 24,
                            KilometerStand = 15320,
                            ReserveringID = 12,
                            StartPostcode = "1234AB",
                            StartStad = "Startstad B",
                            StartStraat = "Startstraat 3B",
                            ToPostcode = "5678BC",
                            ToStad = "Bestemmingstad B",
                            ToStraat = "Bestemmingstraat 3B"
                        },
                        new
                        {
                            Id = 25,
                            KilometerStand = 15400,
                            ReserveringID = 13,
                            StartPostcode = "1234AA",
                            StartStad = "Startstad",
                            StartStraat = "Startstraat 4",
                            ToPostcode = "5678BB",
                            ToStad = "Bestemmingstad",
                            ToStraat = "Bestemmingstraat 4"
                        },
                        new
                        {
                            Id = 26,
                            KilometerStand = 15420,
                            ReserveringID = 13,
                            StartPostcode = "1234AB",
                            StartStad = "Startstad B",
                            StartStraat = "Startstraat 4B",
                            ToPostcode = "5678BC",
                            ToStad = "Bestemmingstad B",
                            ToStraat = "Bestemmingstraat 4B"
                        },
                        new
                        {
                            Id = 27,
                            KilometerStand = 15500,
                            ReserveringID = 14,
                            StartPostcode = "1234AA",
                            StartStad = "Startstad",
                            StartStraat = "Startstraat 5",
                            ToPostcode = "5678BB",
                            ToStad = "Bestemmingstad",
                            ToStraat = "Bestemmingstraat 5"
                        },
                        new
                        {
                            Id = 28,
                            KilometerStand = 15520,
                            ReserveringID = 14,
                            StartPostcode = "1234AB",
                            StartStad = "Startstad B",
                            StartStraat = "Startstraat 5B",
                            ToPostcode = "5678BC",
                            ToStad = "Bestemmingstad B",
                            ToStraat = "Bestemmingstraat 5B"
                        },
                        new
                        {
                            Id = 29,
                            KilometerStand = 15600,
                            ReserveringID = 15,
                            StartPostcode = "1234AA",
                            StartStad = "Startstad",
                            StartStraat = "Startstraat 6",
                            ToPostcode = "5678BB",
                            ToStad = "Bestemmingstad",
                            ToStraat = "Bestemmingstraat 6"
                        },
                        new
                        {
                            Id = 30,
                            KilometerStand = 15620,
                            ReserveringID = 15,
                            StartPostcode = "1234AB",
                            StartStad = "Startstad B",
                            StartStraat = "Startstraat 6B",
                            ToPostcode = "5678BC",
                            ToStad = "Bestemmingstad B",
                            ToStraat = "Bestemmingstraat 6B"
                        },
                        new
                        {
                            Id = 31,
                            KilometerStand = 15700,
                            ReserveringID = 16,
                            StartPostcode = "1234AA",
                            StartStad = "Startstad",
                            StartStraat = "Startstraat 7",
                            ToPostcode = "5678BB",
                            ToStad = "Bestemmingstad",
                            ToStraat = "Bestemmingstraat 7"
                        },
                        new
                        {
                            Id = 32,
                            KilometerStand = 15720,
                            ReserveringID = 16,
                            StartPostcode = "1234AB",
                            StartStad = "Startstad B",
                            StartStraat = "Startstraat 7B",
                            ToPostcode = "5678BC",
                            ToStad = "Bestemmingstad B",
                            ToStraat = "Bestemmingstraat 7B"
                        },
                        new
                        {
                            Id = 33,
                            KilometerStand = 15000,
                            ReserveringID = 17,
                            StartPostcode = "1234AA",
                            StartStad = "Startstad",
                            StartStraat = "Startstraat 0",
                            ToPostcode = "5678BB",
                            ToStad = "Bestemmingstad",
                            ToStraat = "Bestemmingstraat 0"
                        },
                        new
                        {
                            Id = 34,
                            KilometerStand = 15020,
                            ReserveringID = 17,
                            StartPostcode = "1234AB",
                            StartStad = "Startstad B",
                            StartStraat = "Startstraat 0B",
                            ToPostcode = "5678BC",
                            ToStad = "Bestemmingstad B",
                            ToStraat = "Bestemmingstraat 0B"
                        },
                        new
                        {
                            Id = 35,
                            KilometerStand = 15100,
                            ReserveringID = 18,
                            StartPostcode = "1234AA",
                            StartStad = "Startstad",
                            StartStraat = "Startstraat 1",
                            ToPostcode = "5678BB",
                            ToStad = "Bestemmingstad",
                            ToStraat = "Bestemmingstraat 1"
                        },
                        new
                        {
                            Id = 36,
                            KilometerStand = 15120,
                            ReserveringID = 18,
                            StartPostcode = "1234AB",
                            StartStad = "Startstad B",
                            StartStraat = "Startstraat 1B",
                            ToPostcode = "5678BC",
                            ToStad = "Bestemmingstad B",
                            ToStraat = "Bestemmingstraat 1B"
                        },
                        new
                        {
                            Id = 37,
                            KilometerStand = 15200,
                            ReserveringID = 19,
                            StartPostcode = "1234AA",
                            StartStad = "Startstad",
                            StartStraat = "Startstraat 2",
                            ToPostcode = "5678BB",
                            ToStad = "Bestemmingstad",
                            ToStraat = "Bestemmingstraat 2"
                        },
                        new
                        {
                            Id = 38,
                            KilometerStand = 15220,
                            ReserveringID = 19,
                            StartPostcode = "1234AB",
                            StartStad = "Startstad B",
                            StartStraat = "Startstraat 2B",
                            ToPostcode = "5678BC",
                            ToStad = "Bestemmingstad B",
                            ToStraat = "Bestemmingstraat 2B"
                        },
                        new
                        {
                            Id = 39,
                            KilometerStand = 15300,
                            ReserveringID = 20,
                            StartPostcode = "1234AA",
                            StartStad = "Startstad",
                            StartStraat = "Startstraat 3",
                            ToPostcode = "5678BB",
                            ToStad = "Bestemmingstad",
                            ToStraat = "Bestemmingstraat 3"
                        },
                        new
                        {
                            Id = 40,
                            KilometerStand = 15320,
                            ReserveringID = 20,
                            StartPostcode = "1234AB",
                            StartStad = "Startstad B",
                            StartStraat = "Startstraat 3B",
                            ToPostcode = "5678BC",
                            ToStad = "Bestemmingstad B",
                            ToStraat = "Bestemmingstraat 3B"
                        },
                        new
                        {
                            Id = 41,
                            KilometerStand = 15400,
                            ReserveringID = 21,
                            StartPostcode = "1234AA",
                            StartStad = "Startstad",
                            StartStraat = "Startstraat 4",
                            ToPostcode = "5678BB",
                            ToStad = "Bestemmingstad",
                            ToStraat = "Bestemmingstraat 4"
                        },
                        new
                        {
                            Id = 42,
                            KilometerStand = 15420,
                            ReserveringID = 21,
                            StartPostcode = "1234AB",
                            StartStad = "Startstad B",
                            StartStraat = "Startstraat 4B",
                            ToPostcode = "5678BC",
                            ToStad = "Bestemmingstad B",
                            ToStraat = "Bestemmingstraat 4B"
                        },
                        new
                        {
                            Id = 43,
                            KilometerStand = 15500,
                            ReserveringID = 22,
                            StartPostcode = "1234AA",
                            StartStad = "Startstad",
                            StartStraat = "Startstraat 5",
                            ToPostcode = "5678BB",
                            ToStad = "Bestemmingstad",
                            ToStraat = "Bestemmingstraat 5"
                        },
                        new
                        {
                            Id = 44,
                            KilometerStand = 15520,
                            ReserveringID = 22,
                            StartPostcode = "1234AB",
                            StartStad = "Startstad B",
                            StartStraat = "Startstraat 5B",
                            ToPostcode = "5678BC",
                            ToStad = "Bestemmingstad B",
                            ToStraat = "Bestemmingstraat 5B"
                        },
                        new
                        {
                            Id = 45,
                            KilometerStand = 15600,
                            ReserveringID = 23,
                            StartPostcode = "1234AA",
                            StartStad = "Startstad",
                            StartStraat = "Startstraat 6",
                            ToPostcode = "5678BB",
                            ToStad = "Bestemmingstad",
                            ToStraat = "Bestemmingstraat 6"
                        },
                        new
                        {
                            Id = 46,
                            KilometerStand = 15620,
                            ReserveringID = 23,
                            StartPostcode = "1234AB",
                            StartStad = "Startstad B",
                            StartStraat = "Startstraat 6B",
                            ToPostcode = "5678BC",
                            ToStad = "Bestemmingstad B",
                            ToStraat = "Bestemmingstraat 6B"
                        },
                        new
                        {
                            Id = 47,
                            KilometerStand = 15700,
                            ReserveringID = 24,
                            StartPostcode = "1234AA",
                            StartStad = "Startstad",
                            StartStraat = "Startstraat 7",
                            ToPostcode = "5678BB",
                            ToStad = "Bestemmingstad",
                            ToStraat = "Bestemmingstraat 7"
                        },
                        new
                        {
                            Id = 48,
                            KilometerStand = 15720,
                            ReserveringID = 24,
                            StartPostcode = "1234AB",
                            StartStad = "Startstad B",
                            StartStraat = "Startstraat 7B",
                            ToPostcode = "5678BC",
                            ToStad = "Bestemmingstad B",
                            ToStraat = "Bestemmingstraat 7B"
                        });
                });

            modelBuilder.Entity("CovautoAPI.Domain.Entities.Reserveringen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("BoekDatumTot")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("BoekDatumVanaf")
                        .HasColumnType("TEXT");

                    b.Property<int>("LeenAutoID")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ReserveerDatum")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Reserveringen");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BoekDatumTot = new DateTime(2025, 5, 18, 11, 5, 43, 401, DateTimeKind.Local).AddTicks(8136),
                            BoekDatumVanaf = new DateTime(2025, 5, 16, 11, 5, 43, 401, DateTimeKind.Local).AddTicks(7889),
                            LeenAutoID = 1,
                            ReserveerDatum = new DateTime(2025, 5, 6, 11, 5, 43, 399, DateTimeKind.Local).AddTicks(456)
                        },
                        new
                        {
                            Id = 2,
                            BoekDatumTot = new DateTime(2025, 5, 19, 11, 5, 43, 402, DateTimeKind.Local).AddTicks(2502),
                            BoekDatumVanaf = new DateTime(2025, 5, 17, 11, 5, 43, 402, DateTimeKind.Local).AddTicks(2500),
                            LeenAutoID = 1,
                            ReserveerDatum = new DateTime(2025, 5, 7, 11, 5, 43, 402, DateTimeKind.Local).AddTicks(2487)
                        },
                        new
                        {
                            Id = 3,
                            BoekDatumTot = new DateTime(2025, 5, 20, 11, 5, 43, 402, DateTimeKind.Local).AddTicks(2598),
                            BoekDatumVanaf = new DateTime(2025, 5, 18, 11, 5, 43, 402, DateTimeKind.Local).AddTicks(2597),
                            LeenAutoID = 1,
                            ReserveerDatum = new DateTime(2025, 5, 8, 11, 5, 43, 402, DateTimeKind.Local).AddTicks(2595)
                        },
                        new
                        {
                            Id = 4,
                            BoekDatumTot = new DateTime(2025, 5, 21, 11, 5, 43, 402, DateTimeKind.Local).AddTicks(2642),
                            BoekDatumVanaf = new DateTime(2025, 5, 19, 11, 5, 43, 402, DateTimeKind.Local).AddTicks(2641),
                            LeenAutoID = 1,
                            ReserveerDatum = new DateTime(2025, 5, 9, 11, 5, 43, 402, DateTimeKind.Local).AddTicks(2640)
                        },
                        new
                        {
                            Id = 5,
                            BoekDatumTot = new DateTime(2025, 5, 22, 11, 5, 43, 402, DateTimeKind.Local).AddTicks(2664),
                            BoekDatumVanaf = new DateTime(2025, 5, 20, 11, 5, 43, 402, DateTimeKind.Local).AddTicks(2663),
                            LeenAutoID = 1,
                            ReserveerDatum = new DateTime(2025, 5, 10, 11, 5, 43, 402, DateTimeKind.Local).AddTicks(2661)
                        },
                        new
                        {
                            Id = 6,
                            BoekDatumTot = new DateTime(2025, 5, 23, 11, 5, 43, 402, DateTimeKind.Local).AddTicks(2688),
                            BoekDatumVanaf = new DateTime(2025, 5, 21, 11, 5, 43, 402, DateTimeKind.Local).AddTicks(2687),
                            LeenAutoID = 1,
                            ReserveerDatum = new DateTime(2025, 5, 11, 11, 5, 43, 402, DateTimeKind.Local).AddTicks(2685)
                        },
                        new
                        {
                            Id = 7,
                            BoekDatumTot = new DateTime(2025, 5, 24, 11, 5, 43, 402, DateTimeKind.Local).AddTicks(2715),
                            BoekDatumVanaf = new DateTime(2025, 5, 22, 11, 5, 43, 402, DateTimeKind.Local).AddTicks(2714),
                            LeenAutoID = 1,
                            ReserveerDatum = new DateTime(2025, 5, 12, 11, 5, 43, 402, DateTimeKind.Local).AddTicks(2712)
                        },
                        new
                        {
                            Id = 8,
                            BoekDatumTot = new DateTime(2025, 5, 25, 11, 5, 43, 402, DateTimeKind.Local).AddTicks(2736),
                            BoekDatumVanaf = new DateTime(2025, 5, 23, 11, 5, 43, 402, DateTimeKind.Local).AddTicks(2735),
                            LeenAutoID = 1,
                            ReserveerDatum = new DateTime(2025, 5, 13, 11, 5, 43, 402, DateTimeKind.Local).AddTicks(2733)
                        },
                        new
                        {
                            Id = 9,
                            BoekDatumTot = new DateTime(2025, 5, 18, 11, 5, 43, 402, DateTimeKind.Local).AddTicks(2758),
                            BoekDatumVanaf = new DateTime(2025, 5, 16, 11, 5, 43, 402, DateTimeKind.Local).AddTicks(2756),
                            LeenAutoID = 2,
                            ReserveerDatum = new DateTime(2025, 5, 6, 11, 5, 43, 402, DateTimeKind.Local).AddTicks(2755)
                        },
                        new
                        {
                            Id = 10,
                            BoekDatumTot = new DateTime(2025, 5, 19, 11, 5, 43, 402, DateTimeKind.Local).AddTicks(2781),
                            BoekDatumVanaf = new DateTime(2025, 5, 17, 11, 5, 43, 402, DateTimeKind.Local).AddTicks(2780),
                            LeenAutoID = 2,
                            ReserveerDatum = new DateTime(2025, 5, 7, 11, 5, 43, 402, DateTimeKind.Local).AddTicks(2779)
                        },
                        new
                        {
                            Id = 11,
                            BoekDatumTot = new DateTime(2025, 5, 20, 11, 5, 43, 402, DateTimeKind.Local).AddTicks(2803),
                            BoekDatumVanaf = new DateTime(2025, 5, 18, 11, 5, 43, 402, DateTimeKind.Local).AddTicks(2802),
                            LeenAutoID = 2,
                            ReserveerDatum = new DateTime(2025, 5, 8, 11, 5, 43, 402, DateTimeKind.Local).AddTicks(2800)
                        },
                        new
                        {
                            Id = 12,
                            BoekDatumTot = new DateTime(2025, 5, 21, 11, 5, 43, 402, DateTimeKind.Local).AddTicks(2903),
                            BoekDatumVanaf = new DateTime(2025, 5, 19, 11, 5, 43, 402, DateTimeKind.Local).AddTicks(2902),
                            LeenAutoID = 2,
                            ReserveerDatum = new DateTime(2025, 5, 9, 11, 5, 43, 402, DateTimeKind.Local).AddTicks(2901)
                        },
                        new
                        {
                            Id = 13,
                            BoekDatumTot = new DateTime(2025, 5, 22, 11, 5, 43, 402, DateTimeKind.Local).AddTicks(2927),
                            BoekDatumVanaf = new DateTime(2025, 5, 20, 11, 5, 43, 402, DateTimeKind.Local).AddTicks(2925),
                            LeenAutoID = 2,
                            ReserveerDatum = new DateTime(2025, 5, 10, 11, 5, 43, 402, DateTimeKind.Local).AddTicks(2924)
                        },
                        new
                        {
                            Id = 14,
                            BoekDatumTot = new DateTime(2025, 5, 23, 11, 5, 43, 402, DateTimeKind.Local).AddTicks(2948),
                            BoekDatumVanaf = new DateTime(2025, 5, 21, 11, 5, 43, 402, DateTimeKind.Local).AddTicks(2947),
                            LeenAutoID = 2,
                            ReserveerDatum = new DateTime(2025, 5, 11, 11, 5, 43, 402, DateTimeKind.Local).AddTicks(2945)
                        },
                        new
                        {
                            Id = 15,
                            BoekDatumTot = new DateTime(2025, 5, 24, 11, 5, 43, 402, DateTimeKind.Local).AddTicks(2974),
                            BoekDatumVanaf = new DateTime(2025, 5, 22, 11, 5, 43, 402, DateTimeKind.Local).AddTicks(2973),
                            LeenAutoID = 2,
                            ReserveerDatum = new DateTime(2025, 5, 12, 11, 5, 43, 402, DateTimeKind.Local).AddTicks(2972)
                        },
                        new
                        {
                            Id = 16,
                            BoekDatumTot = new DateTime(2025, 5, 25, 11, 5, 43, 402, DateTimeKind.Local).AddTicks(2999),
                            BoekDatumVanaf = new DateTime(2025, 5, 23, 11, 5, 43, 402, DateTimeKind.Local).AddTicks(2998),
                            LeenAutoID = 2,
                            ReserveerDatum = new DateTime(2025, 5, 13, 11, 5, 43, 402, DateTimeKind.Local).AddTicks(2996)
                        },
                        new
                        {
                            Id = 17,
                            BoekDatumTot = new DateTime(2025, 5, 18, 11, 5, 43, 402, DateTimeKind.Local).AddTicks(3027),
                            BoekDatumVanaf = new DateTime(2025, 5, 16, 11, 5, 43, 402, DateTimeKind.Local).AddTicks(3026),
                            LeenAutoID = 3,
                            ReserveerDatum = new DateTime(2025, 5, 6, 11, 5, 43, 402, DateTimeKind.Local).AddTicks(3024)
                        },
                        new
                        {
                            Id = 18,
                            BoekDatumTot = new DateTime(2025, 5, 19, 11, 5, 43, 402, DateTimeKind.Local).AddTicks(3056),
                            BoekDatumVanaf = new DateTime(2025, 5, 17, 11, 5, 43, 402, DateTimeKind.Local).AddTicks(3055),
                            LeenAutoID = 3,
                            ReserveerDatum = new DateTime(2025, 5, 7, 11, 5, 43, 402, DateTimeKind.Local).AddTicks(3054)
                        },
                        new
                        {
                            Id = 19,
                            BoekDatumTot = new DateTime(2025, 5, 20, 11, 5, 43, 402, DateTimeKind.Local).AddTicks(3082),
                            BoekDatumVanaf = new DateTime(2025, 5, 18, 11, 5, 43, 402, DateTimeKind.Local).AddTicks(3081),
                            LeenAutoID = 3,
                            ReserveerDatum = new DateTime(2025, 5, 8, 11, 5, 43, 402, DateTimeKind.Local).AddTicks(3080)
                        },
                        new
                        {
                            Id = 20,
                            BoekDatumTot = new DateTime(2025, 5, 21, 11, 5, 43, 402, DateTimeKind.Local).AddTicks(3143),
                            BoekDatumVanaf = new DateTime(2025, 5, 19, 11, 5, 43, 402, DateTimeKind.Local).AddTicks(3142),
                            LeenAutoID = 3,
                            ReserveerDatum = new DateTime(2025, 5, 9, 11, 5, 43, 402, DateTimeKind.Local).AddTicks(3140)
                        },
                        new
                        {
                            Id = 21,
                            BoekDatumTot = new DateTime(2025, 5, 22, 11, 5, 43, 402, DateTimeKind.Local).AddTicks(3168),
                            BoekDatumVanaf = new DateTime(2025, 5, 20, 11, 5, 43, 402, DateTimeKind.Local).AddTicks(3167),
                            LeenAutoID = 3,
                            ReserveerDatum = new DateTime(2025, 5, 10, 11, 5, 43, 402, DateTimeKind.Local).AddTicks(3166)
                        },
                        new
                        {
                            Id = 22,
                            BoekDatumTot = new DateTime(2025, 5, 23, 11, 5, 43, 402, DateTimeKind.Local).AddTicks(3194),
                            BoekDatumVanaf = new DateTime(2025, 5, 21, 11, 5, 43, 402, DateTimeKind.Local).AddTicks(3193),
                            LeenAutoID = 3,
                            ReserveerDatum = new DateTime(2025, 5, 11, 11, 5, 43, 402, DateTimeKind.Local).AddTicks(3192)
                        },
                        new
                        {
                            Id = 23,
                            BoekDatumTot = new DateTime(2025, 5, 24, 11, 5, 43, 402, DateTimeKind.Local).AddTicks(3219),
                            BoekDatumVanaf = new DateTime(2025, 5, 22, 11, 5, 43, 402, DateTimeKind.Local).AddTicks(3218),
                            LeenAutoID = 3,
                            ReserveerDatum = new DateTime(2025, 5, 12, 11, 5, 43, 402, DateTimeKind.Local).AddTicks(3216)
                        },
                        new
                        {
                            Id = 24,
                            BoekDatumTot = new DateTime(2025, 5, 25, 11, 5, 43, 402, DateTimeKind.Local).AddTicks(3242),
                            BoekDatumVanaf = new DateTime(2025, 5, 23, 11, 5, 43, 402, DateTimeKind.Local).AddTicks(3241),
                            LeenAutoID = 3,
                            ReserveerDatum = new DateTime(2025, 5, 13, 11, 5, 43, 402, DateTimeKind.Local).AddTicks(3240)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
