// <auto-generated />
using System;
using CovautoAPI.Domain.Klasse;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CovautoAPI.Domain.Migrations
{
    [DbContext(typeof(CovautoContext))]
    [Migration("20250509091828_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("CovautoAPI.Domain.Entities.LeenAuto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Kenteken")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("KilometerStand")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("LeenAuto");
                });

            modelBuilder.Entity("CovautoAPI.Domain.Entities.ReserveringData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("KilometerStand")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ReserveringID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StartPostcode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StartStad")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StartStraat")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ToPostcode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ToStad")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ToStraat")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ReserveringData");
                });

            modelBuilder.Entity("CovautoAPI.Domain.Entities.Reserveringen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("BoekDatumTot")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("BoekDatumVanaf")
                        .HasColumnType("TEXT");

                    b.Property<int>("LeenAutoID")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ReserveerDatum")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Reservingen");
                });
#pragma warning restore 612, 618
        }
    }
}
