// <auto-generated />
using System;
using CovautoAPI.Domain.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CovautoAPI.API.Migrations
{
    [DbContext(typeof(CovautoContext))]
    partial class CovautoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("CovautoAPI.Domain.Entities.Collega", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("collega");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Naam = "Sophie Janssen"
                        },
                        new
                        {
                            Id = 2,
                            Naam = "Tom Vermeer"
                        },
                        new
                        {
                            Id = 3,
                            Naam = "Lotte de Vries"
                        });
                });

            modelBuilder.Entity("CovautoAPI.Domain.Entities.LeenAuto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Kenteken")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("KilometerStand")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("leenAutos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Kenteken = "AA-123-AA",
                            KilometerStand = 10000
                        },
                        new
                        {
                            Id = 2,
                            Kenteken = "BB-234-BB",
                            KilometerStand = 20000
                        },
                        new
                        {
                            Id = 3,
                            Kenteken = "CC-345-CC",
                            KilometerStand = 30000
                        });
                });

            modelBuilder.Entity("CovautoAPI.Domain.Entities.ReserveringData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Afstand")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ReserveringID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StartPostcode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StartStad")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StartStraat")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ToPostcode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ToStad")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ToStraat")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("reserveringData");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Afstand = 15,
                            ReserveringID = 1,
                            StartPostcode = "1234AB",
                            StartStad = "StadA",
                            StartStraat = "Startstraat 1-1",
                            ToPostcode = "5678CD",
                            ToStad = "StadB",
                            ToStraat = "Tostraat 1-1"
                        },
                        new
                        {
                            Id = 2,
                            Afstand = 5,
                            ReserveringID = 1,
                            StartPostcode = "2233EF",
                            StartStad = "StadC",
                            StartStraat = "Startstraat 1-2",
                            ToPostcode = "8899GH",
                            ToStad = "StadD",
                            ToStraat = "Tostraat 1-2"
                        },
                        new
                        {
                            Id = 3,
                            Afstand = 15,
                            ReserveringID = 2,
                            StartPostcode = "1234AB",
                            StartStad = "StadA",
                            StartStraat = "Startstraat 2-1",
                            ToPostcode = "5678CD",
                            ToStad = "StadB",
                            ToStraat = "Tostraat 2-1"
                        },
                        new
                        {
                            Id = 4,
                            Afstand = 5,
                            ReserveringID = 2,
                            StartPostcode = "2233EF",
                            StartStad = "StadC",
                            StartStraat = "Startstraat 2-2",
                            ToPostcode = "8899GH",
                            ToStad = "StadD",
                            ToStraat = "Tostraat 2-2"
                        },
                        new
                        {
                            Id = 5,
                            Afstand = 15,
                            ReserveringID = 3,
                            StartPostcode = "1234AB",
                            StartStad = "StadA",
                            StartStraat = "Startstraat 3-1",
                            ToPostcode = "5678CD",
                            ToStad = "StadB",
                            ToStraat = "Tostraat 3-1"
                        },
                        new
                        {
                            Id = 6,
                            Afstand = 5,
                            ReserveringID = 3,
                            StartPostcode = "2233EF",
                            StartStad = "StadC",
                            StartStraat = "Startstraat 3-2",
                            ToPostcode = "8899GH",
                            ToStad = "StadD",
                            ToStraat = "Tostraat 3-2"
                        },
                        new
                        {
                            Id = 7,
                            Afstand = 15,
                            ReserveringID = 4,
                            StartPostcode = "1234AB",
                            StartStad = "StadA",
                            StartStraat = "Startstraat 4-1",
                            ToPostcode = "5678CD",
                            ToStad = "StadB",
                            ToStraat = "Tostraat 4-1"
                        },
                        new
                        {
                            Id = 8,
                            Afstand = 5,
                            ReserveringID = 4,
                            StartPostcode = "2233EF",
                            StartStad = "StadC",
                            StartStraat = "Startstraat 4-2",
                            ToPostcode = "8899GH",
                            ToStad = "StadD",
                            ToStraat = "Tostraat 4-2"
                        },
                        new
                        {
                            Id = 9,
                            Afstand = 15,
                            ReserveringID = 5,
                            StartPostcode = "1234AB",
                            StartStad = "StadA",
                            StartStraat = "Startstraat 5-1",
                            ToPostcode = "5678CD",
                            ToStad = "StadB",
                            ToStraat = "Tostraat 5-1"
                        },
                        new
                        {
                            Id = 10,
                            Afstand = 5,
                            ReserveringID = 5,
                            StartPostcode = "2233EF",
                            StartStad = "StadC",
                            StartStraat = "Startstraat 5-2",
                            ToPostcode = "8899GH",
                            ToStad = "StadD",
                            ToStraat = "Tostraat 5-2"
                        },
                        new
                        {
                            Id = 11,
                            Afstand = 15,
                            ReserveringID = 6,
                            StartPostcode = "1234AB",
                            StartStad = "StadA",
                            StartStraat = "Startstraat 6-1",
                            ToPostcode = "5678CD",
                            ToStad = "StadB",
                            ToStraat = "Tostraat 6-1"
                        },
                        new
                        {
                            Id = 12,
                            Afstand = 5,
                            ReserveringID = 6,
                            StartPostcode = "2233EF",
                            StartStad = "StadC",
                            StartStraat = "Startstraat 6-2",
                            ToPostcode = "8899GH",
                            ToStad = "StadD",
                            ToStraat = "Tostraat 6-2"
                        },
                        new
                        {
                            Id = 13,
                            Afstand = 15,
                            ReserveringID = 7,
                            StartPostcode = "1234AB",
                            StartStad = "StadA",
                            StartStraat = "Startstraat 7-1",
                            ToPostcode = "5678CD",
                            ToStad = "StadB",
                            ToStraat = "Tostraat 7-1"
                        },
                        new
                        {
                            Id = 14,
                            Afstand = 5,
                            ReserveringID = 7,
                            StartPostcode = "2233EF",
                            StartStad = "StadC",
                            StartStraat = "Startstraat 7-2",
                            ToPostcode = "8899GH",
                            ToStad = "StadD",
                            ToStraat = "Tostraat 7-2"
                        },
                        new
                        {
                            Id = 15,
                            Afstand = 15,
                            ReserveringID = 8,
                            StartPostcode = "1234AB",
                            StartStad = "StadA",
                            StartStraat = "Startstraat 8-1",
                            ToPostcode = "5678CD",
                            ToStad = "StadB",
                            ToStraat = "Tostraat 8-1"
                        },
                        new
                        {
                            Id = 16,
                            Afstand = 5,
                            ReserveringID = 8,
                            StartPostcode = "2233EF",
                            StartStad = "StadC",
                            StartStraat = "Startstraat 8-2",
                            ToPostcode = "8899GH",
                            ToStad = "StadD",
                            ToStraat = "Tostraat 8-2"
                        },
                        new
                        {
                            Id = 17,
                            Afstand = 15,
                            ReserveringID = 9,
                            StartPostcode = "1234AB",
                            StartStad = "StadA",
                            StartStraat = "Startstraat 9-1",
                            ToPostcode = "5678CD",
                            ToStad = "StadB",
                            ToStraat = "Tostraat 9-1"
                        },
                        new
                        {
                            Id = 18,
                            Afstand = 5,
                            ReserveringID = 9,
                            StartPostcode = "2233EF",
                            StartStad = "StadC",
                            StartStraat = "Startstraat 9-2",
                            ToPostcode = "8899GH",
                            ToStad = "StadD",
                            ToStraat = "Tostraat 9-2"
                        },
                        new
                        {
                            Id = 19,
                            Afstand = 15,
                            ReserveringID = 10,
                            StartPostcode = "1234AB",
                            StartStad = "StadA",
                            StartStraat = "Startstraat 10-1",
                            ToPostcode = "5678CD",
                            ToStad = "StadB",
                            ToStraat = "Tostraat 10-1"
                        },
                        new
                        {
                            Id = 20,
                            Afstand = 5,
                            ReserveringID = 10,
                            StartPostcode = "2233EF",
                            StartStad = "StadC",
                            StartStraat = "Startstraat 10-2",
                            ToPostcode = "8899GH",
                            ToStad = "StadD",
                            ToStraat = "Tostraat 10-2"
                        },
                        new
                        {
                            Id = 21,
                            Afstand = 15,
                            ReserveringID = 11,
                            StartPostcode = "1234AB",
                            StartStad = "StadA",
                            StartStraat = "Startstraat 11-1",
                            ToPostcode = "5678CD",
                            ToStad = "StadB",
                            ToStraat = "Tostraat 11-1"
                        },
                        new
                        {
                            Id = 22,
                            Afstand = 5,
                            ReserveringID = 11,
                            StartPostcode = "2233EF",
                            StartStad = "StadC",
                            StartStraat = "Startstraat 11-2",
                            ToPostcode = "8899GH",
                            ToStad = "StadD",
                            ToStraat = "Tostraat 11-2"
                        },
                        new
                        {
                            Id = 23,
                            Afstand = 15,
                            ReserveringID = 12,
                            StartPostcode = "1234AB",
                            StartStad = "StadA",
                            StartStraat = "Startstraat 12-1",
                            ToPostcode = "5678CD",
                            ToStad = "StadB",
                            ToStraat = "Tostraat 12-1"
                        },
                        new
                        {
                            Id = 24,
                            Afstand = 5,
                            ReserveringID = 12,
                            StartPostcode = "2233EF",
                            StartStad = "StadC",
                            StartStraat = "Startstraat 12-2",
                            ToPostcode = "8899GH",
                            ToStad = "StadD",
                            ToStraat = "Tostraat 12-2"
                        },
                        new
                        {
                            Id = 25,
                            Afstand = 15,
                            ReserveringID = 13,
                            StartPostcode = "1234AB",
                            StartStad = "StadA",
                            StartStraat = "Startstraat 13-1",
                            ToPostcode = "5678CD",
                            ToStad = "StadB",
                            ToStraat = "Tostraat 13-1"
                        },
                        new
                        {
                            Id = 26,
                            Afstand = 5,
                            ReserveringID = 13,
                            StartPostcode = "2233EF",
                            StartStad = "StadC",
                            StartStraat = "Startstraat 13-2",
                            ToPostcode = "8899GH",
                            ToStad = "StadD",
                            ToStraat = "Tostraat 13-2"
                        },
                        new
                        {
                            Id = 27,
                            Afstand = 15,
                            ReserveringID = 14,
                            StartPostcode = "1234AB",
                            StartStad = "StadA",
                            StartStraat = "Startstraat 14-1",
                            ToPostcode = "5678CD",
                            ToStad = "StadB",
                            ToStraat = "Tostraat 14-1"
                        },
                        new
                        {
                            Id = 28,
                            Afstand = 5,
                            ReserveringID = 14,
                            StartPostcode = "2233EF",
                            StartStad = "StadC",
                            StartStraat = "Startstraat 14-2",
                            ToPostcode = "8899GH",
                            ToStad = "StadD",
                            ToStraat = "Tostraat 14-2"
                        },
                        new
                        {
                            Id = 29,
                            Afstand = 15,
                            ReserveringID = 15,
                            StartPostcode = "1234AB",
                            StartStad = "StadA",
                            StartStraat = "Startstraat 15-1",
                            ToPostcode = "5678CD",
                            ToStad = "StadB",
                            ToStraat = "Tostraat 15-1"
                        },
                        new
                        {
                            Id = 30,
                            Afstand = 5,
                            ReserveringID = 15,
                            StartPostcode = "2233EF",
                            StartStad = "StadC",
                            StartStraat = "Startstraat 15-2",
                            ToPostcode = "8899GH",
                            ToStad = "StadD",
                            ToStraat = "Tostraat 15-2"
                        },
                        new
                        {
                            Id = 31,
                            Afstand = 15,
                            ReserveringID = 16,
                            StartPostcode = "1234AB",
                            StartStad = "StadA",
                            StartStraat = "Startstraat 16-1",
                            ToPostcode = "5678CD",
                            ToStad = "StadB",
                            ToStraat = "Tostraat 16-1"
                        },
                        new
                        {
                            Id = 32,
                            Afstand = 5,
                            ReserveringID = 16,
                            StartPostcode = "2233EF",
                            StartStad = "StadC",
                            StartStraat = "Startstraat 16-2",
                            ToPostcode = "8899GH",
                            ToStad = "StadD",
                            ToStraat = "Tostraat 16-2"
                        },
                        new
                        {
                            Id = 33,
                            Afstand = 15,
                            ReserveringID = 17,
                            StartPostcode = "1234AB",
                            StartStad = "StadA",
                            StartStraat = "Startstraat 17-1",
                            ToPostcode = "5678CD",
                            ToStad = "StadB",
                            ToStraat = "Tostraat 17-1"
                        },
                        new
                        {
                            Id = 34,
                            Afstand = 5,
                            ReserveringID = 17,
                            StartPostcode = "2233EF",
                            StartStad = "StadC",
                            StartStraat = "Startstraat 17-2",
                            ToPostcode = "8899GH",
                            ToStad = "StadD",
                            ToStraat = "Tostraat 17-2"
                        },
                        new
                        {
                            Id = 35,
                            Afstand = 15,
                            ReserveringID = 18,
                            StartPostcode = "1234AB",
                            StartStad = "StadA",
                            StartStraat = "Startstraat 18-1",
                            ToPostcode = "5678CD",
                            ToStad = "StadB",
                            ToStraat = "Tostraat 18-1"
                        },
                        new
                        {
                            Id = 36,
                            Afstand = 5,
                            ReserveringID = 18,
                            StartPostcode = "2233EF",
                            StartStad = "StadC",
                            StartStraat = "Startstraat 18-2",
                            ToPostcode = "8899GH",
                            ToStad = "StadD",
                            ToStraat = "Tostraat 18-2"
                        },
                        new
                        {
                            Id = 37,
                            Afstand = 15,
                            ReserveringID = 19,
                            StartPostcode = "1234AB",
                            StartStad = "StadA",
                            StartStraat = "Startstraat 19-1",
                            ToPostcode = "5678CD",
                            ToStad = "StadB",
                            ToStraat = "Tostraat 19-1"
                        },
                        new
                        {
                            Id = 38,
                            Afstand = 5,
                            ReserveringID = 19,
                            StartPostcode = "2233EF",
                            StartStad = "StadC",
                            StartStraat = "Startstraat 19-2",
                            ToPostcode = "8899GH",
                            ToStad = "StadD",
                            ToStraat = "Tostraat 19-2"
                        },
                        new
                        {
                            Id = 39,
                            Afstand = 15,
                            ReserveringID = 20,
                            StartPostcode = "1234AB",
                            StartStad = "StadA",
                            StartStraat = "Startstraat 20-1",
                            ToPostcode = "5678CD",
                            ToStad = "StadB",
                            ToStraat = "Tostraat 20-1"
                        },
                        new
                        {
                            Id = 40,
                            Afstand = 5,
                            ReserveringID = 20,
                            StartPostcode = "2233EF",
                            StartStad = "StadC",
                            StartStraat = "Startstraat 20-2",
                            ToPostcode = "8899GH",
                            ToStad = "StadD",
                            ToStraat = "Tostraat 20-2"
                        },
                        new
                        {
                            Id = 41,
                            Afstand = 15,
                            ReserveringID = 21,
                            StartPostcode = "1234AB",
                            StartStad = "StadA",
                            StartStraat = "Startstraat 21-1",
                            ToPostcode = "5678CD",
                            ToStad = "StadB",
                            ToStraat = "Tostraat 21-1"
                        },
                        new
                        {
                            Id = 42,
                            Afstand = 5,
                            ReserveringID = 21,
                            StartPostcode = "2233EF",
                            StartStad = "StadC",
                            StartStraat = "Startstraat 21-2",
                            ToPostcode = "8899GH",
                            ToStad = "StadD",
                            ToStraat = "Tostraat 21-2"
                        },
                        new
                        {
                            Id = 43,
                            Afstand = 15,
                            ReserveringID = 22,
                            StartPostcode = "1234AB",
                            StartStad = "StadA",
                            StartStraat = "Startstraat 22-1",
                            ToPostcode = "5678CD",
                            ToStad = "StadB",
                            ToStraat = "Tostraat 22-1"
                        },
                        new
                        {
                            Id = 44,
                            Afstand = 5,
                            ReserveringID = 22,
                            StartPostcode = "2233EF",
                            StartStad = "StadC",
                            StartStraat = "Startstraat 22-2",
                            ToPostcode = "8899GH",
                            ToStad = "StadD",
                            ToStraat = "Tostraat 22-2"
                        },
                        new
                        {
                            Id = 45,
                            Afstand = 15,
                            ReserveringID = 23,
                            StartPostcode = "1234AB",
                            StartStad = "StadA",
                            StartStraat = "Startstraat 23-1",
                            ToPostcode = "5678CD",
                            ToStad = "StadB",
                            ToStraat = "Tostraat 23-1"
                        },
                        new
                        {
                            Id = 46,
                            Afstand = 5,
                            ReserveringID = 23,
                            StartPostcode = "2233EF",
                            StartStad = "StadC",
                            StartStraat = "Startstraat 23-2",
                            ToPostcode = "8899GH",
                            ToStad = "StadD",
                            ToStraat = "Tostraat 23-2"
                        },
                        new
                        {
                            Id = 47,
                            Afstand = 15,
                            ReserveringID = 24,
                            StartPostcode = "1234AB",
                            StartStad = "StadA",
                            StartStraat = "Startstraat 24-1",
                            ToPostcode = "5678CD",
                            ToStad = "StadB",
                            ToStraat = "Tostraat 24-1"
                        },
                        new
                        {
                            Id = 48,
                            Afstand = 5,
                            ReserveringID = 24,
                            StartPostcode = "2233EF",
                            StartStad = "StadC",
                            StartStraat = "Startstraat 24-2",
                            ToPostcode = "8899GH",
                            ToStad = "StadD",
                            ToStraat = "Tostraat 24-2"
                        });
                });

            modelBuilder.Entity("CovautoAPI.Domain.Entities.Reserveringen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("BoekDatumTot")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("BoekDatumVanaf")
                        .HasColumnType("TEXT");

                    b.Property<int>("CollegaID")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("KilometerStandBegin")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("KilometerStandEind")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LeenAutoID")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ReserveerDatum")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("reserveringen");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BoekDatumTot = new DateTime(2024, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BoekDatumVanaf = new DateTime(2024, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CollegaID = 1,
                            LeenAutoID = 1,
                            ReserveerDatum = new DateTime(2024, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            BoekDatumTot = new DateTime(2024, 1, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BoekDatumVanaf = new DateTime(2024, 1, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CollegaID = 1,
                            LeenAutoID = 1,
                            ReserveerDatum = new DateTime(2024, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            BoekDatumTot = new DateTime(2024, 1, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BoekDatumVanaf = new DateTime(2024, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CollegaID = 1,
                            LeenAutoID = 1,
                            ReserveerDatum = new DateTime(2024, 1, 4, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            BoekDatumTot = new DateTime(2024, 1, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BoekDatumVanaf = new DateTime(2024, 1, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CollegaID = 1,
                            LeenAutoID = 1,
                            ReserveerDatum = new DateTime(2024, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            BoekDatumTot = new DateTime(2024, 1, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BoekDatumVanaf = new DateTime(2024, 1, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CollegaID = 1,
                            LeenAutoID = 1,
                            ReserveerDatum = new DateTime(2024, 1, 6, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 6,
                            BoekDatumTot = new DateTime(2024, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BoekDatumVanaf = new DateTime(2024, 1, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CollegaID = 1,
                            LeenAutoID = 1,
                            ReserveerDatum = new DateTime(2024, 1, 7, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 7,
                            BoekDatumTot = new DateTime(2024, 1, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BoekDatumVanaf = new DateTime(2024, 1, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CollegaID = 1,
                            LeenAutoID = 1,
                            ReserveerDatum = new DateTime(2024, 1, 8, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 8,
                            BoekDatumTot = new DateTime(2024, 1, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BoekDatumVanaf = new DateTime(2024, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CollegaID = 1,
                            LeenAutoID = 1,
                            ReserveerDatum = new DateTime(2024, 1, 9, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 9,
                            BoekDatumTot = new DateTime(2024, 1, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BoekDatumVanaf = new DateTime(2024, 1, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CollegaID = 1,
                            LeenAutoID = 2,
                            ReserveerDatum = new DateTime(2024, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 10,
                            BoekDatumTot = new DateTime(2024, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BoekDatumVanaf = new DateTime(2024, 1, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CollegaID = 1,
                            LeenAutoID = 2,
                            ReserveerDatum = new DateTime(2024, 1, 11, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 11,
                            BoekDatumTot = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BoekDatumVanaf = new DateTime(2024, 1, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CollegaID = 1,
                            LeenAutoID = 2,
                            ReserveerDatum = new DateTime(2024, 1, 12, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 12,
                            BoekDatumTot = new DateTime(2024, 1, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BoekDatumVanaf = new DateTime(2024, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CollegaID = 1,
                            LeenAutoID = 2,
                            ReserveerDatum = new DateTime(2024, 1, 13, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 13,
                            BoekDatumTot = new DateTime(2024, 1, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BoekDatumVanaf = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CollegaID = 1,
                            LeenAutoID = 2,
                            ReserveerDatum = new DateTime(2024, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 14,
                            BoekDatumTot = new DateTime(2024, 1, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BoekDatumVanaf = new DateTime(2024, 1, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CollegaID = 1,
                            LeenAutoID = 2,
                            ReserveerDatum = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 15,
                            BoekDatumTot = new DateTime(2024, 1, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BoekDatumVanaf = new DateTime(2024, 1, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CollegaID = 1,
                            LeenAutoID = 2,
                            ReserveerDatum = new DateTime(2024, 1, 16, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 16,
                            BoekDatumTot = new DateTime(2024, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BoekDatumVanaf = new DateTime(2024, 1, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CollegaID = 1,
                            LeenAutoID = 2,
                            ReserveerDatum = new DateTime(2024, 1, 17, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 17,
                            BoekDatumTot = new DateTime(2024, 1, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BoekDatumVanaf = new DateTime(2024, 1, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CollegaID = 1,
                            LeenAutoID = 3,
                            ReserveerDatum = new DateTime(2024, 1, 18, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 18,
                            BoekDatumTot = new DateTime(2024, 1, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BoekDatumVanaf = new DateTime(2024, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CollegaID = 1,
                            LeenAutoID = 3,
                            ReserveerDatum = new DateTime(2024, 1, 19, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 19,
                            BoekDatumTot = new DateTime(2024, 1, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BoekDatumVanaf = new DateTime(2024, 1, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CollegaID = 1,
                            LeenAutoID = 3,
                            ReserveerDatum = new DateTime(2024, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 20,
                            BoekDatumTot = new DateTime(2024, 1, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BoekDatumVanaf = new DateTime(2024, 1, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CollegaID = 1,
                            LeenAutoID = 3,
                            ReserveerDatum = new DateTime(2024, 1, 21, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 21,
                            BoekDatumTot = new DateTime(2024, 1, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BoekDatumVanaf = new DateTime(2024, 1, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CollegaID = 1,
                            LeenAutoID = 3,
                            ReserveerDatum = new DateTime(2024, 1, 22, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 22,
                            BoekDatumTot = new DateTime(2024, 1, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BoekDatumVanaf = new DateTime(2024, 1, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CollegaID = 1,
                            LeenAutoID = 3,
                            ReserveerDatum = new DateTime(2024, 1, 23, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 23,
                            BoekDatumTot = new DateTime(2024, 1, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BoekDatumVanaf = new DateTime(2024, 1, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CollegaID = 1,
                            LeenAutoID = 3,
                            ReserveerDatum = new DateTime(2024, 1, 24, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 24,
                            BoekDatumTot = new DateTime(2024, 1, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BoekDatumVanaf = new DateTime(2024, 1, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CollegaID = 1,
                            LeenAutoID = 3,
                            ReserveerDatum = new DateTime(2024, 1, 25, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
